Added Nachimport Script for Aachen
aktin/aktin-scripts pull request #1
Opened 2024-04-25 12:12 UTC by LongusBongus

2024-05-21 09:33 UTC, akomii requested changes
Review done. Also make sure that each method has static input and return types

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +            raise Exception('Required CSV, got: ' + file_type)
Dont throw generic Exceptions

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +    def __init__(self):
Why are these public?

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        except Exception:
Dont throw generic exceptions

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        self.__logger = Logger()
Why is this a private var?

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        self.__logger = Logger()
Already defined in Parent

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        self.__script_id = os.environ['script_id']
Is this even used?

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +    def _update_table_entry(self, enc_num: int, pat_num: int, entry: DiagnoseData):
Why are all of these methods protected?

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        eid = EncounterIDHandler()
Shouldn't the pipeline be initialized the other way around?

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        os.environ['sourcesystem_cd'] = ('gfi_' + os.environ['script_id']
Why is this deinfed here?

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +                (self._table.c.sourcesystem_cd != os.environ['sourcesystem_cd'])
Why are here rows deleted where the sourcesystem does not match? Isnt this deleting the db data then not related to this script?

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        start_date = datetime.strptime(entry.get_startdate(), '%d.%m.%Y %H:%M:%S').strftime('%Y-%m-%d %H:%M:%S.%f')
helper.convert_date_to_i2b2_format() was exactly created for this reason....

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        removed_num = self._remove_observation_entry(enc_num)
I assume I get the encounter_num, that got removed. But the method returns the number of rows that were removed. So....

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        os.environ['sourcesystem_cd'] = ('gfi_' + os.environ['script_id']
Why is this an environment variable? This is not its purpose...

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +                    modifier_cd='localisation'
Neither the CSV nor the DiagnoseData object has this information....

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +                    concept_cd=diagnose,
The standard database code for ICD is "ICD10GM:{diagnose}"

2024-05-21 09:33 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        inserted_num = self._insert_observation_entry(enc_num, pat_num, entry)
See the same problem as with "removed_num"

2024-05-21 09:42 UTC, akomii requested changes

2024-05-21 09:42 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        self.__logger.increase_updated(removed_num)
What is the purpose of this line?

2024-05-21 09:42 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        if removed_num < inserted_num:
What happens here?

2024-05-21 09:42 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        self.new_imported = 0
new_imported and updated should also be encounter-based

2024-05-22 12:27 UTC, LongusBongus commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +    def _update_table_entry(self, enc_num: int, pat_num: int, entry: DiagnoseData):
This method is a wrapper for the main update class "_update_table_entry". If "_update_table_entry" is called alone, new encounters could be inserted that hadn't existed before and the logger wouldn't count the inserts as well.

2024-05-22 12:38 UTC, LongusBongus commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +                (self._table.c.sourcesystem_cd != os.environ['sourcesystem_cd'])
The idea was to use the source system code to check if this entry has already been edited by this script and not to touch it anymore if that is the case. This was one of the functionalities we set at the beginning of the project. On the other hand the Script requirements should prevent double editing, so if i got your permission i will remove this part.

2024-05-22 13:03 UTC, LongusBongus commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        self.new_imported = 0
I see the problem that one of the requirements of the project was not to insert new encounters, only update existing ones. Additionally the Logger is supposed to log updated and newly inserted entries. If we can't insert new encounters, then we can't count new ones so we decided to count the number of effected diagnoses (updated) and the number of newly inserted diagnoses instead. Maybe i got it wrong so could you explain what exactly "updated" and "new imported" should log?

2024-06-13 09:44 UTC, akomii requested changes
Seems good with me. Adjust the commented changes and it will be good to go

2024-06-13 09:44 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +
The getter and setter here need some rearrangement, keep the getter and setter of the same var close to each other. Also recheck the naming of the vars and methods:

- why is the getter of csv_encounters called  get_num_of_csv_encounters() ?
- why does increase_connected_to_db() increase successful_insert

2024-06-13 09:44 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +
Which Value does this Exception add? The message

```Required CSV, got: ' + file_type```

should already be enough

2024-06-13 09:44 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        elif len(date) == 19:
You can expect, that the date format will be always in German

2024-06-13 09:44 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +    def _update_table_entry(self, enc_num: int, pat_num: int, entry: DiagnoseData):
That does not answer my question. ObservationFactEntryHandler is a class without any further children. So there is no need to use update_table_entry as a protected method. You can make it private instead

2024-06-13 09:44 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +                self._conn.rollback()
What does this do?

2024-06-13 09:44 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +
This method cannot work, because you are creating a transaction but miss to do one key step. No data is actually created in the database

2024-06-13 09:46 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        """
Line 52+53

2024-06-26 09:03 UTC, closed without merging