Bug/nachimport
aktin/aktin-scripts pull request #3
Opened 2024-08-22 13:13 UTC by LongusBongus

2024-09-04 11:02 UTC, akomii requested changes

2024-09-04 11:02 UTC, akomii commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +                print(f'Update operation to {self._table} failed: {traceback.format_exc()}')
Whats the value in catching exactly this exception? Also: Why is there no rollback?? Previously it was just fine:

```python
            except db.exc.SQLAlchemyError:
                self._conn.rollback()
                print(f'Insert operation to {self._table} failed: {traceback.format_exc()}')
```

2024-09-06 08:22 UTC, LongusBongus commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +            data.set_diagnoses(val, is_start_diagnose=True)
Its because if StartICDHandler sets the diagnose in data object, the data are considered start diagnoses. If EndICDHandler inputs data, it is considered as an end diagnose and will therefore not be a startdiagnose. Thats why it is set to False.

2024-09-06 09:00 UTC, LongusBongus commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +                print(f'Update operation to {self._table} failed: {traceback.format_exc()}')
No rollback because connection object has no rollback method. Additionally the error is only thrown when a duplicate entry is being inserted, so there wouldn't be a change to rollback in the first place

2024-09-06 09:10 UTC, LongusBongus commented on generic-file-import-scripts/aktin_nachimporter_ac.py
> +        self.set_main_diagnose(self.__diagnoses[0])
Because the main diagnose needs two entries, one that modifies it as the main diagnose and one with an empty modifier like the rest of the diagnoses, it was easier to make one entry for the main diagnose specifically and then run over all diagnoses and create an entry with an empty modifier. So it was for a shorter insertion code

2024-09-19 12:01 UTC, akomii approved these changes

2024-09-19 12:03 UTC, akomii commented
Bugfix in icd_nachimport_ac.py (ICDs imported via this script throw an exception during report generation)

2024-09-19 12:04 UTC, merged